"""Updated the cascade to delete

Revision ID: 9b59174b5e47
Revises: e70816f7f870
Create Date: 2024-07-09 18:09:36.153870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b59174b5e47'
down_revision = 'e70816f7f870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignments_task_id_tasks', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignments_task_id_tasks'), 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_task_id_tasks'), type_='foreignkey')
        batch_op.create_foreign_key('fk_assignments_task_id_tasks', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
